### PR TITLE
Add modal for login and signup

### PR DESCRIPTION
**Pull request by geflores5**

### CODE REVIEW

**Comment by geflores5** [comment]
Changes login and signup views to partials and renders them in a modal.

**Comment by peterbehere** [comment]
Modals disappear when loaded.

This might have something to do with the <a href="#>Sign-up<a> and the similar one for log-in.
The links when clicked, reload the page, and I think that causes the modal to go away.

**Comment by geflores5** [comment]
Hmm I don't have any issues with them disappearing. I could remove the link entirely, I only had it there to look the same as the other links but we can change that later.

**Comment by geflores5** [comment]
Try again and let me know.

**Comment by VonTeacher** [comment]
Merged file changes via command line. Closing PR.

**Pull request closed without merging**
